// ThaneBridgeStub.swift — Minimal stub so the test target compiles without the Rust FFI.
//
// The real ThaneBridge is auto-generated by UniFFI and requires linking against
// libthane_bridge.a. Tests use this stub instead, providing just enough API surface
// for RustBridge.swift to compile. The RustBridge wrapper gracefully handles
// ThaneBridge init failures (stores as Optional), so tests exercise the pure-Swift
// logic paths.

import Foundation

/// Stub replacement for the UniFFI-generated ThaneBridge class.
/// Methods here match the signatures called via `rustCoreBridge?.…` in RustBridge.swift.
class ThaneBridge {
    struct SandboxCommand {
        let executable: String
        let args: [String]
        let extraEnv: [String]
    }

    init(configPath: String?) throws {
        // Always fail so RustBridge.rustCoreBridge stays nil in tests.
        throw NSError(domain: "ThaneBridgeStub", code: 1,
                      userInfo: [NSLocalizedDescriptionKey: "Stub — no Rust FFI available"])
    }

    func sandboxGetCommand(workspaceId: String, shell: String) -> SandboxCommand? {
        nil
    }
}
