// ThaneBridgeStub.swift — Minimal stub so the test target compiles without the Rust FFI.
//
// The real ThaneBridge is auto-generated by UniFFI and requires linking against
// libthane_bridge.a. Tests use this stub instead, providing just enough API surface
// for RustBridge.swift to compile. The RustBridge wrapper gracefully handles
// ThaneBridge init failures (stores as Optional), so tests exercise the pure-Swift
// logic paths.

import Foundation

/// Stub replacement for the UniFFI-generated ThaneBridge class.
/// Methods here match the signatures called via `rustCoreBridge?.…` in RustBridge.swift.
class ThaneBridge {
    struct SandboxCommand {
        let executable: String
        let args: [String]
        let extraEnv: [String]
    }

    init(configPath: String?) throws {
        // Always fail so RustBridge.rustCoreBridge stays nil in tests.
        throw NSError(domain: "ThaneBridgeStub", code: 1,
                      userInfo: [NSLocalizedDescriptionKey: "Stub — no Rust FFI available"])
    }

    func sandboxGetCommand(workspaceId: String, shell: String) -> SandboxCommand? {
        nil
    }

    // Audit policy accessors — stubs so RustBridge.swift compiles in tests.
    func auditAllowClear() -> Bool { false }
    func auditRetentionDays() -> UInt32 { 90 }
    func clearAuditLogAdmin(reason: String) -> Bool { false }

    /// Stub mirror of UniFFI-generated `AuditVerifyResult`.
    struct AuditVerifyResult {
        let eventsChecked: UInt32
        let verified: Bool
        let failureSummary: String?
    }

    func verifyAuditIntegrity() -> AuditVerifyResult {
        AuditVerifyResult(eventsChecked: 0, verified: true, failureSummary: nil)
    }

    // Phase 5: external sink stubs. All return safe defaults so the Swift
    // panel code can be exercised in tests without a real Rust dispatcher.
    func auditSinkStatusJson() -> String { "{\"sinks\":[]}" }
    func auditDlqListJson(limit: UInt64) -> String {
        "{\"total\":0,\"returned\":0,\"entries\":[]}"
    }
    func auditDlqRetry(sinkFilter: String?, eventId: String?) -> UInt32 { 0 }
    func auditDlqClear() -> Bool { false }
}
