use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use crate::panel::PanelId;

/// A notification generated by a terminal process via OSC sequences.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Notification {
    pub id: Uuid,
    pub panel_id: PanelId,
    pub title: String,
    pub body: String,
    pub urgency: Urgency,
    pub timestamp: DateTime<Utc>,
    pub read: bool,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
#[derive(Default)]
pub enum Urgency {
    Low,
    #[default]
    Normal,
    Critical,
}


impl Notification {
    pub fn new(panel_id: PanelId, title: impl Into<String>, body: impl Into<String>) -> Self {
        Self {
            id: Uuid::new_v4(),
            panel_id,
            title: title.into(),
            body: body.into(),
            urgency: Urgency::Normal,
            timestamp: Utc::now(),
            read: false,
        }
    }
}

/// Store of notifications for a workspace.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct NotificationStore {
    notifications: Vec<Notification>,
    max_count: usize,
}

impl NotificationStore {
    pub fn new(max_count: usize) -> Self {
        Self {
            notifications: Vec::new(),
            max_count,
        }
    }

    pub fn push(&mut self, notification: Notification) {
        self.notifications.push(notification);
        if self.notifications.len() > self.max_count {
            self.notifications.remove(0);
        }
    }

    pub fn unread_count(&self) -> usize {
        self.notifications.iter().filter(|n| !n.read).count()
    }

    pub fn mark_all_read(&mut self) {
        for n in &mut self.notifications {
            n.read = true;
        }
    }

    pub fn mark_read(&mut self, id: Uuid) {
        if let Some(n) = self.notifications.iter_mut().find(|n| n.id == id) {
            n.read = true;
        }
    }

    pub fn all(&self) -> &[Notification] {
        &self.notifications
    }

    pub fn latest(&self) -> Option<&Notification> {
        self.notifications.last()
    }

    pub fn clear(&mut self) {
        self.notifications.clear();
    }

    pub fn for_panel(&self, panel_id: PanelId) -> Vec<&Notification> {
        self.notifications
            .iter()
            .filter(|n| n.panel_id == panel_id)
            .collect()
    }
}

/// Parse OSC notification sequences.
///
/// Supported formats:
/// - OSC 9 ; <message> ST          — iTerm2 notification
/// - OSC 99 ; <params> ; <body> ST — Kitty notification
/// - OSC 777 ; notify ; <title> ; <body> ST — rxvt notification
pub fn parse_osc_notification(osc_number: u32, payload: &str) -> Option<(String, String)> {
    match osc_number {
        9 => {
            // OSC 9: simple notification, entire payload is the message.
            let body = payload.trim().to_string();
            Some(("Notification".to_string(), body))
        }
        99 => {
            // OSC 99: Kitty notification protocol.
            // Format: key=value pairs separated by ; then body after last ;
            // Simplified: just extract body after the last semicolon.
            if let Some(pos) = payload.rfind(';') {
                let body = payload[pos + 1..].trim().to_string();
                let title = "Notification".to_string();
                Some((title, body))
            } else {
                Some(("Notification".to_string(), payload.trim().to_string()))
            }
        }
        777 => {
            // OSC 777: notify;title;body
            let parts: Vec<&str> = payload.splitn(3, ';').collect();
            if parts.len() >= 3 && parts[0] == "notify" {
                Some((parts[1].to_string(), parts[2].to_string()))
            } else if parts.len() >= 2 && parts[0] == "notify" {
                Some(("Notification".to_string(), parts[1].to_string()))
            } else {
                None
            }
        }
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_osc9_notification() {
        let result = parse_osc_notification(9, "Build complete!");
        assert_eq!(
            result,
            Some(("Notification".to_string(), "Build complete!".to_string()))
        );
    }

    #[test]
    fn test_osc777_notification() {
        let result = parse_osc_notification(777, "notify;Build;All tests passed");
        assert_eq!(
            result,
            Some(("Build".to_string(), "All tests passed".to_string()))
        );
    }

    #[test]
    fn test_osc99_notification() {
        let result = parse_osc_notification(99, "i=1;Build complete");
        assert_eq!(
            result,
            Some(("Notification".to_string(), "Build complete".to_string()))
        );
    }

    #[test]
    fn test_notification_store() {
        let mut store = NotificationStore::new(100);
        let panel_id = Uuid::new_v4();

        store.push(Notification::new(panel_id, "Test", "Body 1"));
        store.push(Notification::new(panel_id, "Test", "Body 2"));

        assert_eq!(store.unread_count(), 2);
        store.mark_all_read();
        assert_eq!(store.unread_count(), 0);
    }

    #[test]
    fn test_notification_store_max_count() {
        let mut store = NotificationStore::new(2);
        let panel_id = Uuid::new_v4();

        store.push(Notification::new(panel_id, "1", "a"));
        store.push(Notification::new(panel_id, "2", "b"));
        store.push(Notification::new(panel_id, "3", "c"));

        assert_eq!(store.all().len(), 2);
        assert_eq!(store.all()[0].title, "2");
        assert_eq!(store.all()[1].title, "3");
    }

    #[test]
    fn test_mark_read_specific_id() {
        let mut store = NotificationStore::new(100);
        let panel_id = Uuid::new_v4();

        let n1 = Notification::new(panel_id, "A", "body1");
        let n1_id = n1.id;
        let n2 = Notification::new(panel_id, "B", "body2");
        let n2_id = n2.id;
        store.push(n1);
        store.push(n2);

        assert_eq!(store.unread_count(), 2);
        store.mark_read(n1_id);
        assert_eq!(store.unread_count(), 1);
        // n2 should still be unread
        assert!(!store.all().iter().find(|n| n.id == n2_id).unwrap().read);
    }

    #[test]
    fn test_for_panel_filtering() {
        let mut store = NotificationStore::new(100);
        let panel_a = Uuid::new_v4();
        let panel_b = Uuid::new_v4();

        store.push(Notification::new(panel_a, "A1", "body"));
        store.push(Notification::new(panel_b, "B1", "body"));
        store.push(Notification::new(panel_a, "A2", "body"));

        let panel_a_notifs = store.for_panel(panel_a);
        assert_eq!(panel_a_notifs.len(), 2);
        let panel_b_notifs = store.for_panel(panel_b);
        assert_eq!(panel_b_notifs.len(), 1);
    }

    #[test]
    fn test_latest_empty_and_non_empty() {
        let mut store = NotificationStore::new(100);
        assert!(store.latest().is_none());

        let panel_id = Uuid::new_v4();
        store.push(Notification::new(panel_id, "First", "body"));
        store.push(Notification::new(panel_id, "Second", "body"));

        assert_eq!(store.latest().unwrap().title, "Second");
    }

    #[test]
    fn test_clear() {
        let mut store = NotificationStore::new(100);
        let panel_id = Uuid::new_v4();
        store.push(Notification::new(panel_id, "Test", "body"));
        assert_eq!(store.all().len(), 1);

        store.clear();
        assert_eq!(store.all().len(), 0);
        assert_eq!(store.unread_count(), 0);
        assert!(store.latest().is_none());
    }

    #[test]
    fn test_osc777_title_only_no_body() {
        // OSC 777 with "notify;title" but no body
        let result = parse_osc_notification(777, "notify;Build Done");
        assert_eq!(
            result,
            Some(("Notification".to_string(), "Build Done".to_string()))
        );
    }

    #[test]
    fn test_osc777_not_notify_prefix() {
        // OSC 777 without "notify" prefix — should return None
        let result = parse_osc_notification(777, "something;title;body");
        assert!(result.is_none());
    }

    #[test]
    fn test_osc_unsupported_number() {
        assert!(parse_osc_notification(42, "anything").is_none());
    }
}
